routes/web.php
Route::post('subhead/search', 'Setting\AccountSetting\SubHeadController@search');
Route::post('subhead/delete', 'Setting\AccountSetting\SubHeadController@delete');
Route::post('subhead/subhead', 'Setting\AccountSetting\SubHeadController@get_sub_head');
Route::post('subhead/particular', 'Setting\AccountSetting\SubHeadController@get_particular');

// Resource Route for Particular
Route::get('particular/opening-balance', 'ParticularController@openingBalance');
Route::post('particular/opening-balance/form', 'ParticularController@getOpeningBalanceForm');
Route::post('particular/opening-balance/save_data', 'ParticularController@storeOpeningBalance');

Route::get('particular/ledger/{id}', 'ParticularController@ledger');
Route::post('particular/ledger_search', 'ParticularController@search_ledger');
Route::resource('particulars', 'ParticularController');
Route::get('particular/create/{id}', 'ParticularController@create_particular');
Route::post('particulars/search', 'ParticularController@search');
Route::post('particulars/delete', 'ParticularController@delete');
Route::post('particulars/particular', 'ParticularController@get_particular');

/* Product Delivery Related Route */
Route::get('dellivery/items', 'DeliveryController@sales_itmes');
Route::resource('dellivery', 'DeliveryController');
Route::post('dellivery/itmes/search', 'DeliveryController@sales_itmes_search');
Route::post('dellivery/search', 'DeliveryController@search');
Route::post('dellivery/delete', 'DeliveryController@delete');
Route::get('dellivery/{id}/confirm', 'DeliveryController@confirm');
Route::get('dellivery/{id}/reset', 'DeliveryController@reset');
Route::get('dellivery/gatepass/{id}', 'DeliveryController@gatepass');
Route::post('dellivery/add_item', 'DeliveryController@add_item');
Route::get('dellivery/itemlist/{id}', 'DeliveryController@itemlist');
Route::get('dellivery/remove_item/{id}', 'DeliveryController@remove_item');
Route::post('dellivery/search_itemlist', 'DeliveryController@search_itemlist');
Route::get('dellivery/item_edit/{id}', 'DeliveryController@edit_item');
Route::post('dellivery/update_item/', 'DeliveryController@update_item');
Route::post('search_product/', 'DeliveryController@search_product');

// Party
Route::resource('/party', 'Setting\Party\PartyController');
Route::post('/party/search', 'Setting\Party\PartyController@search');
Route::post('/party/delete', 'Setting\Party\PartyController@delete');

// unit size
Route::resource('unit_size', 'Setting\ProductModule\UnitSizeController');
Route::post('unit_size/search', 'Setting\ProductModule\UnitSizeController@search');
Route::post('unit_size/delete', 'Setting\ProductModule\UnitSizeController@delete');
Route::post('unit_size/prod_type', 'Setting\ProductModule\UnitSizeController@prod_typeByInstitute');
Route::post('unit_size/size_list', 'Setting\ProductModule\UnitSizeController@sizeList');

// Rent Releted Routes
Route::resource('/rent', 'Setting\RentSetting\RentController');
Route::post('rent/search', 'Setting\RentSetting\RentController@search');
Route::post('rent/delete', 'Setting\RentSetting\RentController@delete');
Route::post('rent/categoryByType', 'Setting\RentSetting\RentController@categoryListByType');
Route::post('rent/productByCategory', 'Setting\RentSetting\RentController@productListByCategory');
Route::post('rent/product_sizeByUnit', 'Setting\RentSetting\RentController@product_sizeByUnit');

//stock
Route::resource('stock', 'StockController');

//Party Commission
Route::resource('/party_commission', 'Setting\PartyCommission\PartyCommissionController');
Route::post('/party_commission/search', 'Setting\PartyCommission\PartyCommissionController@search');
Route::post('/party_commission/delete', 'Setting\PartyCommission\PartyCommissionController@delete');
Route::post('/party_commission/partyListByType', 'Setting\PartyCommission\PartyCommissionController@partyListByType');
Route::post('/party_commission/categoryListByType', 'Setting\PartyCommission\PartyCommissionController@categoryListByType');
Route::post('/party_commission/productByCategory', 'Setting\PartyCommission\PartyCommissionController@productListByCategory');
Route::post('/party_commission/unitSizeByUnit', 'Setting\\artyCommission\PartyCommissionController@unitSizeByUnit');


//party rent
Route::resource('/party_rent', 'Setting\PartyCommission\PartyRentController');
Route::post('/party_rent/search', 'Setting\PartyCommission\PartyRentController@search');
Route::post('/party_rent/delete', 'Setting\PartyCommission\PartyRentController@delete');
Route::post('/party_rent/PartyNameByType', 'Setting\PartyCommission\PartyRentController@PartyNameByType');
Route::post('/party_rent/ProductByCategory', 'Setting\PartyCommission\PartyRentController@ProductByCategory');
Route::post('/party_rent/UnitSizeByUnit', 'Setting\PartyCommission\PartyRentController@UnitSizeByUnit');
Route::post('/party_rent/DataSave', 'Setting\PartyCommission\PartyRentController@DataSave');
Route::post('/party_rent/search_itemlist/list', 'Setting\PartyCommission\PartyRentController@search_itemlist');
Route::post('/party_rent/remove/item', 'Setting\PartyCommission\PartyRentController@remove_item');


//party commision multi
Route::resource('/party_commission_multi', 'Setting\PartyCommission\PartyCommissionMultiController');
Route::post('/party_commission_multi/search', 'Setting\PartyCommission\PartyCommissionMultiController@search');
Route::post('/party_commission_multi/delete', 'Setting\PartyCommission\PartyCommissionMultiController@delete');
Route::post('/party_commission_multi/PartyNameByType', 'Setting\PartyCommission\PartyCommissionMultiController@PartyNameByType');
Route::post('/party_commission_multi/ProductByCategory', 'Setting\PartyCommission\PartyCommissionMultiController@ProductByCategory');
Route::post('/party_commission_multi/UnitSizeByUnit', 'Setting\PartyCommission\PartyCommissionMultiController@UnitSizeByUnit');
Route::post('/party_commission_multi/DataSave', 'Setting\PartyCommission\PartyCommissionMultiController@DataSave');
Route::post('/party_commission_multi/itemList/createdLoanList', 'Setting\PartyCommissio\/PartyCommissionMultiController@createdLoanList');
Route::post('/party_commission_multi/currentItem/update', 'Setting\PartyCommission\PartyCommissionMultiController@currentItemUpdate');




//Delivery condition
Route::resource('/delivery_condition', 'Setting\DeleverySetting\DeliveryConditionController');
Route::post('/delivery_condition/search', 'Setting\DeleverySetting\DeliveryConditionController@search');
Route::post('/delivery_condition/delete', 'Setting\DeleverySetting\DeliveryConditionController@delete');

// DSR routes
Route::get('/dsr', 'HomeController@dsr_index');
Route::get('/dsr/home', 'HomeController@dsr_index');


//party Loan
Route::resource('/party_loan', 'Setting\PartyCommission\PartyLoanController');
Route::post('/party_loan/search', 'Setting\PartyCommission\PartyLoanController@search');
Route::post('/party_loan/delete', 'Setting\PartyCommission\PartyLoanController@delete');
Route::post('/party_laon/partyListByType', 'Setting\PartyCommission\PartyLoanController@partyListByType');
Route::post('/party_loan/ProductByCategory', 'Setting\PartyCommission\PartyLoanController@ProductByCategory');
Route::post('/party_loan/UnitSizeByUnit', 'Setting\PartyCommission\PartyLoanController@UnitSizeByUnit');
Route::post('/party_loan/DataSave', 'Setting\PartyCommission\PartyLoanController@DataSave');
Route::post('/party_loan/itemList/createdLoanList', 'Setting\PartyCommission\PartyLoanController@createdLoanList');
Route::post('/party_loan/currentItem/update', 'Setting\PartyCommission\PartyLoanController@currentItemUpdate');

// Advance Loan Payment
Route::get('/loan/advance/payment_create', 'AdvanceLoanPaymentController@index');
Route::post('/advance/loan/payment/agent_list', 'AdvanceLoanPaymentController@agentInformation');
Route::post('/advance/loan/payment/bag_type_ist', 'AdvanceLoanPaymentController@getBagTypeInformation');

// Sr Setting
Route::resource('/sr/setting', 'SrSettingController');

// Sr 
Route::resource('/sr', 'SrController');
Route::post('/sr/search', 'SrController@search');
Route::post('/sr/delete', 'SrController@delete');

//Bank Transaction related routes
Route::resource('/bank_transaction', 'Accounts\BankTransactionController');
Route::post('/bank_transaction/delete', 'Accounts\BankTransactionController@delete');
Route::post('/bank_transaction/search', 'Accounts\BankTransactionController@search');
Route::post('bank_transaction/ledger', 'Accounts\BankTransactionController@show');


//Cash_transaction related routes
Route::resource('/cash_transaction', 'Accounts\CashTransactionController');
Route::post('/cash_transaction/delete', 'Accounts\CashTransactionController@delete');
Route::post('/cash_transaction/search', 'Accounts\CashTransactionController@search');
Route::post('/cash_transaction/account', 'Accounts\CashTransactionController@AccountByBank');

// Resource Route for AccountHead 
Route::resource('/account_head', 'Accounts\AccountHeadController');
Route::post('account_head/search', 'Accounts\AccountHeadController@search');
Route::post('account_head/delete', 'Accounts\AccountHeadController@delete');
Route::post('account_head/ledger', 'Accounts\AccountHeadController@show');
Route::post('account_head/subhead_dropdown_list', 'Accounts\AccountHeadController@subhead_dropdown_list');
Route::post('account_head/max_id/get/', 'Accounts\AccountHeadController@getMaxId')->name('head.getMaxId');


Route::resource('requisition', 'Accounts\RequisitionController');
Route::post('requisition/delete', 'Accounts\RequisitionController@delete');
Route::post('requisition/search', 'Accounts\RequisitionController@search');


Route::resource('product_in_create', 'DailyWork\ProductInCreateController');
Route::post('product_in_create/delete', 'DailyWork\ProductInCreateController@delete');
Route::post('product_in_create/search', 'DailyWork\ProductInCreateController@search');

app/Models/Setting/PartyCommission/PartyRent.php
<?php

namespace App\Models\Setting\PartyCommission;

use Illuminate\Database\Eloquent\Model;

class PartyRent extends Model {

    protected $table = 'party_rent';
    public $timestamps = false;

    public static function model($className = __CLASS__) {
        return new $className();
    }

    public function company() {
        return $this->belongsTo('App\Models\Institute', 'company_id', 'id');
    }

    public function product_type() {
        return $this->belongsTo('App\Models\ProductType', 'product_type_id', 'id');
    }
     public function party_type() {
        return $this->belongsTo('App\Models\Setting\Party\PartyType', 'party_type_id', 'id');
    }
    public function party() {
        return $this->belongsTo('App\Models\Setting\Party\Party', 'party_id', 'id');
    }
    public function categories() {
        return $this->belongsTo('App\Models\Setting\ProductModule\Category', 'category_id', 'id');
    }
    public function products() {
        return $this->belongsTo('App\Models\Setting\ProductModule\Product', 'product_id', 'id');
    }

    public function units() {
        return $this->belongsTo('App\Models\Setting\ProductModule\Unit', 'unit_id', 'id');
    }
     public function UnitSize() {
        return $this->belongsTo('App\Models\Setting\ProductModule\UnitSize', 'unit_size_id', 'id');
    }
 
    public function rent_types(){
        return $this->belongsTo('App\Models\Setting\RentSetting\RentType', 'rent_type_id', 'id');
    }
     public function rent(){
        return $this->belongsTo('App\Models\Setting\RentSetting\Rent', 'rent_id', 'id');
    }

    public function stock() {
        return $this->hasMany('App\Models\Main\Stock', 'category_id', 'id');
    }

    public function product_transfer() {
        return $this->hasMany('App\Models\Main\ProductTransfer', 'category_id', 'id');
    }

    public function ricesales_item() {
        return $this->belongsTo('App\Models\Main\SalesOrderItem', 'category_id', 'id');
    }

    public function ricepurchases_item() {
        return $this->hasMany('App\Models\Main\RicePurchasesItem', 'category_id', 'id');
    }

    public function rawsales_item() {
        return $this->hasMany('App\Models\Main\RawSalesItem', 'category_id', 'id');
    }

    public function paddyPurchases_item() {
        return $this->hasMany('App\Models\Main\PurchaseItem', 'category_id', 'id');
    }

    public function getList($comId = null) {
        $_query = $this->where('is_deleted', 0);
        if (!is_null($comId)) {
            $_query->where('company_id', $comId);
        }
        $_dataset = $_query->get();
        return !empty($_dataset) ? $_dataset : null;
    }

    public function custom_labels() {
        return [
            "id" => "ID",
            "business_type_id" => "Business Type",
            "type" => "Type",
            "name" => "Name",
            "unit" => "Unit",
            "description" => "Description",
        ];
    }

    public function tableColumnsAsLabel() {
        $_arr = [];
        $columns = $this->getTableColumns();
        foreach ($columns as $ck => $cv) {
            $_arr[$cv] = $cv;
        }
        return $_arr;
    }

    public function getTableColumns() {
        return $this->getConnection()->getSchemaBuilder()->getColumnListing($this->getTable());
    }

}

resources/views/party_rent/_list.blade.php
@if (!empty($dataset) && count($dataset) > 0)
<div class="table-responsive">
     <table class="table table-bordered tbl_thin" id="check">
                <tr class="bg-info" id="r_checkAll">
                    <th class="text-center" style="width:3%;">#</th>
                    <th>Party Type</th>
                    <th>Party Name</th>
                    <th>Category</th>
                    <th>Product</th>
                    <th>Unit</th>
                    <th>Unit Size</th>
                    <th>Rent</th>
                    <th class="text-center hip" style="width: 8%;">Actions</th>
                    <th class="text-center hip" style="width: 3%;"><input type="checkbox" id="check_all" value="all"></th>
                </tr>
                <?php
                $counter = 0;
                if (isset($_GET['page']) && $_GET['page'] > 1) {
                    $counter = ($_GET['page'] - 1) * $dataset->perPage();
                }
                ?>
                @forelse ($dataset as $data)
                    <?php $counter++; ?>
                    <tr onmouseover="change_color(this, true)" onmouseout="change_color(this, false)">
                    <td class="text-center">{{ $counter }}</td>
                    <td>{{ !empty($data->party_type) ? $data->party_type->party_type : "" }}</td>
                    <td>{{ !empty($data->party) ? $data->party->name : "" }}</td>
                    <td>{{ !empty($data->categories) ? $data->categories->name : "" }}</td>
                    <td>{{ !empty($data->products) ? $data->products->name : "" }}</td>
                    <td>{{ !empty($data->units) ? $data->units->unit : ""}}</td>
                    <td>{{ !empty($data->UnitSize) ? $data->UnitSize->name : "" }}</td>
                    <td>{{ $data->rent }}</td>
                        <td class="text-center hip">
                            @if (has_user_access('party_rent_edit'))
                                <a class="btn btn-info btn-xs" href="party_rent/{{ $data->id }}/edit">Edit</a>
                            @endif
                        </td>
                        <td class="text-center hip">
                            @if (has_user_access('party_rent_delete'))
                                <input type="checkbox" name="data[]" value="{{ $data->id }}">
                            @endif
                        </td>
                    </tr>
               
                @empty
                    <tr>
                        <td class="text-center" colspan="7"> No records found </td>
                    </tr>
                @endforelse
            </table>
           
</div>
<div class="text-center hip">
    {{ $dataset->render() }}
</div>
@else
<div class="alert alert-info">No records found!</div>
@endif

resources/views/party_rent/create.blade.php
@extends('layouts.app')

@section('breadcrumbs')
<div id="breadcrumbBar" class="breadcrumb site_nav_links no_bdr_rad clearfix">
    <div class="col-md-3 col-sm-3 col-xs-2 no_pad">
        <button class="btn btn-info btn-xs" type="button" onclick="history.back()" title="Go Back"><span class="visible-xs"><i class="fa fa-arrow-left"></i></span><span class="hidden-xs">Back</span></button>
        <button class="btn btn-info btn-xs" onclick="redirectTo('<?= url('party_rent/create'); ?>')" title="Refresh" type="button"><span class="visible-xs"><i class="fa fa-refresh"></i></span><span class="hidden-xs">Refresh</span></button>
    </div>
    <div class="col-md-6 col-sm-6 hidden-xs text-center">
        <h2 class="page-title">{{$breadcrumb_title}}</h2>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-10 no_pad">
        <ul class="text-right no_mrgn no_pad">
            <li><a href="{{ url('/home') }}">Home</a> <i class="fa fa-angle-right"></i></li>
            <li><a href="{{ url('/party_rent') }}">Party Rent</a> <i class="fa fa-angle-right"></i></li>
            <li>Form</li>
        </ul>
    </div>
</div>
@endsection

@section('content')
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Enter Party Rent</h3>
    </div>
    <div class="panel-body">
        <div class="form-group col-md-2">
            <select class="form-control select2search" id="party_type_id" name="party_type_id" required>
                <option value="">Select party Type</option>
                @foreach($party_type as $type)
                <option value="{{$type->id}}">{{$type->party_type}}</option>
                @endforeach
            </select>
            <small class="text-danger">{{ $errors->first('party_type') }}</small>
        </div>
        <div class="form-group col-md-2">
            <select class="form-control select2search" id="party_id" name="party_id">
                <option value="">Select Party</option>
            </select>
            <small class="text-danger">{{ $errors->first('party_rent') }}</small>
        </div>
        <div class="form-group col-md-2">
            <select class="form-control select2search" id="category_id" name="category_id">
                <option value="">Select Category</option>
                @foreach($categories as $category)
                <option value="{{ $category->id }}">{{ $category->name }}</option>
                @endforeach
            </select>
            <small class="text-danger">{{ $errors->first('category') }}</small>
        </div>
        <div class="form-group col-md-2">
            <select class="form-control select2search" id="product_id" name="product_id">
                <option value="">Select Product</option>

            </select>
            <small class="text-danger">{{ $errors->first('product') }}</small>
        </div>
        <div class="form-group col-md-2">
            <select class="form-control select2search" id="unit_id" name="unit_id" required>
                <option value="">Select Unit</option>
                @foreach($units as $unit)
                <option value="{{$unit->id}}">{{$unit->unit}}</option>
                @endforeach
            </select>
            <small class="text-danger">{{ $errors->first('unit') }}</small>
        </div>
        <div class="form-group col-md-2">
            <select class="form-control select2search" id="unit_size_id" name="unit_size_id" required>
                <option value="">Select Unit Size</option>

            </select>
            <small class="text-danger">{{ $errors->first('unit_size') }}</small>
        </div>
        <div class="form-group col-md-1">
            <input type="text" class="form-control" id="rent" name="rent" placeholder="rent" required>
            <small class="text-danger">{{ $errors->first('rent') }}</small>
        </div>
        <div class="form-group col-md-1">
            <button style="padding: 5px;" class="text-center"><span id="addRowItem" style="border-radius:50%;color:white; cursor: pointer; padding:5px;background:#383838"><i class="fa fa-plus"></i></span></button>
        </div>
    </div>
</div>
<div class="clearfix">
    <div class="clearfix" id="item_list">
        <table class="table table-bordered tbl_thin" style="margin: 0">
            <tr class="bg-primary">
                <th class="text-center"><span>Party rent details</span></th>
            </tr>
        </table>
        <form id="frmList" action="{{  route('party_rent.store') }}">
            <div class="table-responsive">
                <table class="table table-bordered tbl_thin" id="check">
                    <thead>
                        <tr class="bg-info" id="r_checkAll">
                            <th>Party Type</th>
                            <th>Party Name</th>
                            <th>Category</th>
                            <th>Product</th>
                            <th>Unit</th>
                            <th>Unit Size</th>
                            <th>Rent</th>
                            <th class="text-center" style="width: 3%;"></th>
                        </tr>
                    </thead>
                    <tbody id="rentitems">

                    </tbody>
                </table>
            </div>
        </form>
    </div>
</div>

<div class="text-center" style="margin-top:10px;">
    <button id="itemInsertBtn" class="btn btn-primary xsw_100" disabled>Save</button>
</div>
<script type="text/javascript">    
    // Dropdown Validation
    const isDropdownSelected = () => {
        let status = true;
        if ($('#party_type_id').val() === '') {
            toastr.error('Please select Party Type dropdown');
            status = false;
        }
        if ($('#party_id').val() === '') {
            toastr.error('Please select Party dropdown');
            status = false;
        }
        if ($('#category_id').val() === '') {
            toastr.error('Please select Category dropdown');
            status = false;
        }
        if ($('#product_id').val() === '') {
            toastr.error('Please select Product dropdown');
            status = false;
        }
        if ($('#unit_id').val() === '') {
            toastr.error('Please select Unit dropdown');
            status = false;
        }
        if ($('#unit_size_id').val() === '') {
            toastr.error('Please select Unit Size dropdown');
            status = false;
        }
        if ($('#rent').val() === '') {
            toastr.error('rent must be required!!ty');
            status = false;
        }
        return status;
    }

    var addedProductId = [];
    const addItemId = () => {
        let object        = {};
        let partyId       = $("#party_id").val();
        let productId     = $("#product_id").val();
        let unitId          = $("#unit_id").val()
        object["partyId"]   = partyId;
        object["productId"]   = productId;
        object["unitId"]   = unitId;
    
        addedProductId.push(object);
        enable(itemInsertBtn);
    }

    // Table Data generate Function
    const getDomeUi = () => {
        addItemId();
        return `<tr>
        <td>${$('#party_type_id option:selected').text()}
            <input class="party_type_id" data-id="${$('#party_type_id').val()}"  type="hidden" name="party_type_id[]" value="${$('#party_type_id').val()}">
        </td>
        <td>${$('#party_id option:selected').text()}
            <input class="party_id" data-id="${$('#party_id').val()}"  type="hidden" name="party_id[]" value="${$('#party_id').val()}">
        </td>
        <td>${$('#category_id option:selected').text()}
            <input class="category_id" data-id="${$('#category_id').val()}"  type="hidden" name="category_id[]" value="${$('#category_id').val()}">
        </td>
        <td>${$('#product_id option:selected').text()}
            <input class="product_id" data-id="${$('#product_id').val()}"  type="hidden" name="product_id[]" value="${$('#product_id').val()}">
        </td>
        <td>${$('#unit_id option:selected').text()}
            <input class="unit_id" data-id="${$('#unit_id').val()}"  type="hidden" name="unit_id[]" value="${$('#unit_id').val()}">
        </td>
        <td>${$('#unit_size_id option:selected').text()}
            <input class="unit_size_id" data-id="${$('#unit_size_id').val()}"  type="hidden" name="unit_size_id[]" value="${$('#unit_size_id').val()}">
        </td>
        <td>${$('#rent').val()}<input style="display:none" type="number" name="rent[]" value="${ $('#rent').val() }" class="form-control rent" placeholder="Amount" readonly ></td>
        <td><i id='deleteItem' class='fa fa-trash' role='button'></i></td>
        </tr>`;
    }

    // Table Row Create function
    const addRow = () => {
        if (isDropdownSelected() === false) {
            return false;
        }
        for (let item of addedProductId) {
            if (item["partyId"] == $('#party_id').val() && item["productId"] == $('#product_id').val() && item["unitId"] == $("#unit_id").val()) {
                toastr.warning('Item already added');
                return false;
            }
        }
        document
            .querySelector("#rentitems")
            .insertAdjacentHTML("beforeend", getDomeUi());
    }

    // Table Row Remove
    const removeRow = () => {
        $(document).on("click", "#deleteItem", function() {
            let partyId = $(this).parents('tr').find('.party_id').data('id');
            let productId = $(this).parents('tr').find('.product_id').data('id');
            let unitId = $(this).parents('tr').find('.unit_id').data('id');
            for (let index in addedProductId) {
                if (addedProductId[index]["partyId"] == partyId) {
                    addedProductId.splice(index, 1)
                }
               else if (addedProductId[index]["productId"] == productId) {
                    addedProductId.splice(index, 1)
                }
               else if (addedProductId[index]["unitId"] == unitId) {
                    addedProductId.splice(index, 1)
                }
            }
            $(this).parents("tr").remove();
            toastr.success("Record Deleted Successfully!");
            disable(itemInsertBtn);
        })
    }

    // Table Row Insert Function
    const processOnSubmit = () => {
        let url = "{{ route('party_rent.store') }}";
        let itemForm = $("#frmList").serialize();
       
        axios.post(url,itemForm)
        .then((response) => {
            toastr.success(response.data);
            window.onbeforeunload = true;
            
                window.location = "{{ route('party_rent.index') }}";
            
        })
        .catch((error) => {
            toastr.error("Something went Wrong!");
        })
    }

        $(document).on("click", "#itemInsertBtn", function(e) {
        disable(itemInsertBtn);
        return true;
        e.preventDefault();
    });

    //     $(document).on("change", "#party_type_id", function() {
    //     enable(itemInsertBtn);
    //     return true;
    // });

    // Table Row Create and Save Btn click function
    $(document).ready(function() {
        $('#addRowItem').click(addRow)
        removeRow();
        $('#itemInsertBtn').click(function() {
            processOnSubmit();
        })
    })

    //on change on party type  to party 
    $(document).on("change", "#party_type_id", function() {
        var _partyType = $("#party_type_id").val();
        $.ajax({
            url: "{{ URL::to('party_laon/partyListByType') }}",
            type: "post",
            data: {
                _token: csrfToken,
                partyTypeId: _partyType
            },
            success: function(res) {
                $('#party_id').html(res);
            },
            error: function(xhr, status) {
                alert('There is some error.Try after some time.');
            }
        });

    });

    //on change on category to product
    $(document).on("change", "#category_id", function() {
        var _productType = $("#category_id").val();
        $.ajax({
            url: "{{ URL::to('/party_rent/ProductByCategory') }}",
            type: "post",
            data: {
                _token: csrfToken,
                productTypeId: _productType
            },
            success: function(res) {
                $('#product_id').html(res);
            },
            error: function(xhr, status) {
                alert('There is some error.Try after some time.');
            }
        });

    });

    //on change on unit to unit size
    $(document).on("change", "#unit_id", function() {
        var _Unit_id = $("#unit_id").val();
        $.ajax({
            url: "{{ URL::to('/party_rent/UnitSizeByUnit') }}",
            type: "post",
            data: {
                _token: csrfToken,
                UnitSizeId: _Unit_id
            },
            success: function(res) {
                $('#unit_size_id').html(res);
            },
            error: function(xhr, status) {
                alert('There is some error.Try after some time.');
            }
        });

    });

</script>
@endsection